### ISSUE TITLE
Build for Qt6 (`org.kde.Platform//6.x`)

### ISSUE THREAD

**Issue by zefr0x** [flathub/org.kde.KStyle.Kvantum#16]
Some apps uses `Qt6` and there are more and more apps moving to it. I think that there should be a build for `org.kde.Platform//6.x`.

Knowing that `Kvantum` support both `Qt5` and `Qt6`.

**Comment by zer0-x** [comment]
I think now it's possible to build it just for Qt6 without requiring Qt5.

Source: https://github.com/tsujan/Kvantum/issues/875#issuecomment-1506347182

**Comment by eylles** [comment]
sorry to bother, but is there any progress for this? i'm having to actively mask some flatpaks to keep them in the 5.15-22.08 runtime just to have proper themeing on my system.

is there anything that can be done to help with building for 6.x ?
