### ISSUE TITLE
Build for `org.kde.Platform//5.15-23.08`

### ISSUE THREAD

**Issue by zefr0x** [flathub/org.kde.KStyle.Kvantum#22]
There‘s no available build for org.kde.Platform//5.15-23.08. Is it possible to add a build for this version of org.kde.Platform?

**Comment by meow-d** [comment]
i tried changing this line here to `23.08` and building it, and it worked. i'm not experienced with flatpak so i don't know what other steps need to be taken, but it's very possible.

https://github.com/flathub/org.kde.KStyle.Kvantum/blob/99bd94846f662b5de5cc9680f89fee8c318e1dc9/org.kde.KStyle.Kvantum.json#L7

**Comment by HugLifeTiZ** [comment]
It looks like the process to get this to actually show up for folks mainly comprises someone with commit access to the repository making a new branch called `branch/5.15-23.08` that just changes the runtime version. I'm not sure if that's the sort of thing we could do with a pull request?

**Comment by meow-d** [comment]
yooo thanks. and we can close the issue now.
